<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AutoCompleteForm</RootNamespace>
    <AssemblyName>AutoCompleteForm</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dict1AndDict2">
      <HintPath>..\libs\Dict1AndDict2.dll</HintPath>
    </Reference>
    <Reference Include="MedicalEquipmentTester">
      <HintPath>..\libs\MedicalEquipmentTester.dll</HintPath>
    </Reference>
    <Reference Include="WorkOrder">
      <HintPath>..\libs\WorkOrder.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
